name: Test, Build and Deploy | Modul 02 - Lab3.3 Senior Project

on:
  push:
    branches: [main]

jobs:
  test-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Testing Build pre-Deploy
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm i
      - run: npm run build

    deploy:
      needs: test-build
      runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version: [16.x]

      steps:
        - name: Build app on VM
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.PASSWORD }}
            script: |
              eval "$(ssh-agent -s)"
              ssh-add ~/.ssh/<<private_key>>
              echo "Cek folder project";
              [ ! -d "${HOME}/senpro/482306/modul02/<<project_name>>/" ] &&
              {
                echo "Repository belum di-clone. Cloning...";
                mkdir -p ~/senpro/482306/modul02;
                cd ~/senpro/482306/modul02;
                git clone <<repo_url>>;
              } || 
              {
                echo "Repository sudah ada. Building...";
                cd ~/senpro/482306/modul02/<<project_name>>;
                git restore .;
                git pull origin main;
              }